# Generated by Django 3.1.4 on 2021-01-02 17:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Surname', models.CharField(max_length=20)),
                ('phone_Number', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(regex='^(0|\\+)\\d{8,15}$')])),
                ('Email', models.EmailField(max_length=254)),
                ('Id_No', models.IntegerField(unique=True)),
                ('DOB', models.DateField(auto_now_add=True)),
                ('Occupation', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOfTheGroup', models.CharField(max_length=50, unique=True)),
                ('ChairOfGroup', models.CharField(max_length=50)),
                ('Treasurer', models.CharField(max_length=50)),
                ('TPNumber', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(regex='^(0|\\+)\\d{8,15}$')])),
                ('YOE', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LoanBorrowed', models.IntegerField()),
                ('IsActive', models.BooleanField(default=True)),
                ('AppliedOn', models.DateField(auto_now_add=True)),
                ('TimeDue', models.DateField(auto_now_add=True)),
                ('ClientName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bims_app.client')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Business_No', models.CharField(max_length=20)),
                ('NameOfBusiness', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(regex='^(0|\\+)\\d{8,15}$')])),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bims_app.client')),
            ],
        ),
    ]
