# Generated by Django 3.1.4 on 2021-01-31 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims_app', '0002_auto_20210105_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='BusinessName',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='bims_app.business'),
            preserve_default=False,
        ),
    ]
