# Generated by Django 3.1.4 on 2021-02-06 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bims_app', '0003_loans_businessname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsActive', models.BooleanField(default=True)),
                ('AppliedOn', models.DateField(auto_now_add=True)),
                ('TimeDue', models.DateField(auto_now_add=True)),
                ('ClientName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bims_app.client')),
            ],
        ),
        migrations.RenameField(
            model_name='loans',
            old_name='LoanBorrowed',
            new_name='Amount',
        ),
        migrations.RenameField(
            model_name='loans',
            old_name='IsActive',
            new_name='isActive',
        ),
        migrations.RemoveField(
            model_name='loans',
            name='AppliedOn',
        ),
        migrations.RemoveField(
            model_name='loans',
            name='BusinessName',
        ),
        migrations.RemoveField(
            model_name='loans',
            name='ClientName',
        ),
        migrations.RemoveField(
            model_name='loans',
            name='TimeDue',
        ),
        migrations.AddField(
            model_name='loans',
            name='CratedOn',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='Loan_Duration',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loans',
            name='Loan_Name',
            field=models.CharField(default=True, max_length=99),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.AddField(
            model_name='application',
            name='Loan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bims_app.loans'),
        ),
    ]
